module.exports = {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary": "#4d626c",
        "tertiary-dim": "#51516c",
        "primary-dim": "#325383",
        "on-secondary": "#f2faff",
        "surface-tint": "#3e5f90",
        "secondary-fixed-dim": "#c1d8e4",
        "on-tertiary": "#fbf7ff",
        "on-primary-fixed-variant": "#3b5c8d",
        "on-background": "#323232",
        "surface-container-highest": "#e4e2e2",
        "on-primary-container": "#315282",
        "on-secondary-fixed-variant": "#495f69",
        "primary": "#3e5f90",
        "secondary-fixed": "#cfe6f2",
        "tertiary-fixed-dim": "#cdccec",
        "error": "#9f403d",
        "surface-bright": "#fcf9f8",
        "on-tertiary-fixed-variant": "#555571",
        "inverse-on-surface": "#9e9c9c",
        "on-tertiary-container": "#4c4c67",
        "outline": "#7b7a7a",
        "on-error": "#fff7f6",
        "inverse-primary": "#a7c8ff",
        "surface-variant": "#e4e2e2",
        "outline-variant": "#b3b2b1",
        "surface": "#fcf9f8",
        "primary-fixed-dim": "#bed5ff",
        "primary-container": "#d5e3ff",
        "surface-container": "#f0eded",
        "surface-container-lowest": "#ffffff",
        "background": "#fcf9f8",
        "on-primary": "#f6f7ff",
        "on-surface-variant": "#5f5f5f",
        "on-error-container": "#752121",
        "on-tertiary-fixed": "#393953",
        "surface-container-low": "#f6f3f2",
        "surface-dim": "#dbdad9",
        "secondary-dim": "#415660",
        "error-dim": "#4e0309",
        "inverse-surface": "#0e0e0e",
        "primary-fixed": "#d5e3ff",
        "on-primary-fixed": "#1c406e",
        "tertiary-fixed": "#dbdafb",
        "tertiary": "#5d5d78",
        "on-secondary-fixed": "#2d424c",
        "secondary-container": "#cfe6f2",
        "on-secondary-container": "#40555f",
        "on-surface": "#323232",
        "error-container": "#fe8983",
        "tertiary-container": "#dbdafb",
        "surface-container-high": "#eae8e7"
      },
      fontFamily: {
        "headline": ["Manrope", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
    },
  },
  plugins: [],
}
